baseURL = 'https://josestg.com/'
languageCode = 'en-us'
title = 'Jose Sitanggang'
paginate = 5

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
description = "'m a software engineer from Indonesia. It's great to have you on my site, where I share my learning journey and thoughts on software engineering, math, and more"
keywords = ["Jose Sitanggang", "Software Engineering", "Backend Engineer"]
DateFormat = "January 2, 2006"
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
showtoc = true
tocopen = false
ShareButtons = ["twitter", "facebook", "linkedin", "whatsapp"]
comments = true

[params.label]
text = "josestg"

[params.homeInfoParams]
Title = "ðŸ‘‹ Meet Jose Sitanggang"
Content = "I'm a software engineer. It's great to have you on my site, where I share my learning journey and thoughts on software engineering, math, and more. I'd love to hear your thoughts, so please feel free to share your feedback!"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[params.giscus]
repo = 'josestg/josestg'                  # see https://giscus.app for more details
repoId = 'R_kgDOKlwNbQ'
category = 'post-comments'
categoryId = 'DIC_kwDOKlwNbc4Cae2C'
mapping = 'pathname'
theme = 'dark_dimmed'
lang = 'en'

[params.editPost]
URL = "https://github.com/josestg/josestg/blob/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = false
